name: release

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: okteto/aspnetcore-getting-started:dev
          target: dev
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: okteto/aspnetcore-getting-started:hello-world
